### PR TITLE
fix: use correct imports for optional fields

### LINKED ISSUE #896: TS error if .proto file has the same message name as imported
### Dependencies 

- ts-proto@1.156.2
- typescript@5.1.6
- protobufjs@7.2.4

### Problem description

There is `common/common.proto` which has `FindOptions` message

```proto
syntax = "proto3";
package common;

message FindOptions {
  repeated string sort = 1;
  int32 page_num = 2;
  int32 page_size = 3;
}
```

and `items/items.proto` which has `FindOptions` too. Also `items.proto` imports `common.proto` and uses `common.FindOptions` message inside their own `FindOptions` message.

```proto
syntax = "proto3";
import "common/common.proto";

package content.items;

message FindOptions {
  common.FindOptions options = 2;
  bool regular = 4;
  bool hidden = 5;
  bool templates = 6;
}

message FindRequest {
  string space_id = 1;
  FindOptions options = 5;
}
```

Finally during the build process we have TS error

<details>
  <summary>(spoiler) config/dist/items/items.ts(1511,27): error TS2345: Argument of type 'import("/builds/perxis/perxis- 
  js/config/dist/items/items").FindOptions' is not assignable to parameter of type 'import("/builds/perxis/perxis- 
  js/config/dist/common/common").FindOptions'.</summary>
  
  ```
  config/dist/items/items.ts(1511,27): error TS2345: Argument of type 'import("/builds/perxis/perxis- 
  js/config/dist/items/items").FindOptions' is not assignable to parameter of type 'import("/builds/perxis/perxis- 
  js/config/dist/common/common").FindOptions'.
  Type 'FindOptions' is missing the following properties from type 'FindOptions': sort, pageNum, pageSize, fields, excludeFields
  config/dist/items/items.ts(1540,11): error TS2739: Type 'FindOptions' is missing the following properties from type 
  'FindOptions': deleted, regular, hidden, templates
config/dist/items/items.ts(1584,5): error TS2322: Type 'import("/builds/perxis/perxis-js/config/dist/common/common").FindOptions | undefined' is not assignable to type 'import("/builds/perxis/perxis-js/config/dist/items/items").FindOptions | undefined'.
  Type 'import("/builds/perxis/perxis-js/config/dist/common/common").FindOptions' is not assignable to type 'import("/builds/perxis/perxis-js/config/dist/items/items").FindOptions'.
config/dist/items/items.ts(1585,34): error TS2559: Type '{ options?: ... | undefined; deleted?: boolean | undefined; regular?: boolean | undefined; hidden?: boolean | undefined; templates?: boolean | undefined; }' has no properties in common with type '{ sort?: string[] | undefined; pageNum?: number | undefined; pageSize?: number | undefined; fields?: string[] | undefined; excludeFields?: boolean | undefined; }'.
config/dist/items/items.ts(1883,27): error TS2345: Argument of type 'import("/builds/perxis/perxis-js/config/dist/items/items").FindOptions' is not assignable to parameter of type 'import("/builds/perxis/perxis-js/config/dist/common/common").FindOptions'.
config/dist/items/items.ts(1912,11): error TS2322: Type 'import("/builds/perxis/perxis-js/config/dist/common/common").FindOptions' is not assignable to type 'import("/builds/perxis/perxis-js/config/dist/items/items").FindOptions'.
config/dist/items/items.ts(1956,5): error TS2322: Type 'import("/builds/perxis/perxis-js/config/dist/common/common").FindOptions | undefined' is not assignable to type 'import("/builds/perxis/perxis-js/config/dist/items/items").FindOptions | undefined'.
config/dist/items/items.ts(1957,34): error TS2559: Type '{ options?: ... | undefined; deleted?: boolean | undefined; regular?: boolean | undefined; hidden?: boolean | undefined; templates?: boolean | undefined; }' has no properties in common with type '{ sort?: string[] | undefined; pageNum?: number | undefined; pageSize?: number | undefined; fields?: string[] | undefined; excludeFields?: boolean | undefined; }'.
config/dist/items/items.ts([197](https://git.perx.ru/perxis/perxis-js/-/jobs/105621#L197)4,27): error TS2345: Argument of type 'import("/builds/perxis/perxis-js/config/dist/items/items").FindOptions' is not assignable to parameter of type 'import("/builds/perxis/perxis-js/config/dist/common/common").FindOptions'.
config/dist/items/items.ts([199](https://git.perx.ru/perxis/perxis-js/-/jobs/105621#L199)1,11): error TS2322: Type 'import("/builds/perxis/perxis-js/config/dist/common/common").FindOptions' is not assignable to type 'import("/builds/perxis/perxis-js/config/dist/items/items").FindOptions'.
config/dist/items/items.ts([200](https://git.perx.ru/perxis/perxis-js/-/jobs/105621#L200)7,5): error TS2322: Type 'import("/builds/perxis/perxis-js/config/dist/common/common").FindOptions | undefined' is not assignable to type 'import("/builds/perxis/perxis-js/config/dist/items/items").FindOptions | undefined'.
config/dist/items/items.ts(2008,34): error TS2559: Type '{ options?: ... | undefined; deleted?: boolean | undefined; regular?: boolean | undefined; hidden?: boolean | undefined; templates?: boolean | undefined; }' has no properties in common with type '{ sort?: string[] | undefined; pageNum?: number | undefined; pageSize?: number | undefined; fields?: string[] | undefined; excludeFields?: boolean | undefined; }'.
config/dist/items/items.ts([202](https://git.perx.ru/perxis/perxis-js/-/jobs/105621#L202)1,27): error TS2345: Argument of type 'import("/builds/perxis/perxis-js/config/dist/items/items").FindOptions' is not assignable to parameter of type 'import("/builds/perxis/perxis-js/config/dist/common/common").FindOptions'.
config/dist/items/items.ts([203](https://git.perx.ru/perxis/perxis-js/-/jobs/105621#L203)8,11): error TS2322: Type 'import("/builds/perxis/perxis-js/config/dist/common/common").FindOptions' is not assignable to type 'import("/builds/perxis/perxis-js/config/dist/items/items").FindOptions'.
config/dist/items/items.ts([205](https://git.perx.ru/perxis/perxis-js/-/jobs/105621#L205)4,5): error TS2322: Type 'import("/builds/perxis/perxis-js/config/dist/common/common").FindOptions | undefined' is not assignable to type 'import("/builds/perxis/perxis-js/config/dist/items/items").FindOptions | undefined'.
config/dist/items/items.ts(2055,34): error TS2559: Type '{ options?: ... | undefined; deleted?: boolean | undefined; regular?: boolean | undefined; hidden?: boolean | undefined; templates?: boolean | undefined; }' has no properties in common with type '{ sort?: string[] | undefined; pageNum?: number | undefined; pageSize?: number | undefined; fields?: string[] | undefined; excludeFields?: boolean | undefined; }'.
```
</details>

The problem that final `items.d.ts` file doesn't imports `FindOptions` from `common` at all

image

so inside `items.d.ts` `FindOptions` interface refers on themself 

image

I have similar story with `Filter` message, which also exists in both files, but inside `items.proto` it is used with `repeated`, and in final `items.d.ts` it imported correctly, with rename to `Filter1` as you can see on the image above.

### PR DESCRIPTION
**Pull request by andrehp**
It seems that the ts-poet.Code.toString() changes the struct and it was causing the code gen to fail to use the correct imports in some situations.

Added a struct which was failing to compile before the fix.

This should fix #896

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -873,9 +873,6 @@ function generateInterfaceDeclaration(
     const name = maybeSnakeToCamel(fieldDesc.name, options);
     const isOptional = isOptionalProperty(fieldDesc, messageDesc.options, options);
     const type = toTypeName(ctx, messageDesc, fieldDesc, isOptional);
-    if (isOptional && !type.toString().includes("undefined")) {
```
Comment (andrehp) [inline src/main.ts:876]: The definitive fix probably lays within ts-poet, I believe the toString method shouldn't have any side-effects

Comment (stephenh) [reply src/main.ts:876]: Wow, I agree that is very strange that `toString` has side-effects. Also kinda funny this `console.warn` was just hanging out here :shrug: . Thanks for finding! I'll see if I can poke around at the ts-poet root cause at some point...

**Review by stephenh — APPROVED** [review]
Ah great, thanks @andrewparmet !
